### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by StevenReitsma** [StevenReitsma/athlos#1]
- [x] View profile
- [x] View list with all possible achievements (sorted by category, search option)
- [x] Start/stop activity
- [x] Add achievements to watchlist, view watchlist, remove from watchlist
- [x] View ranking
- [x] Dashboard, recommended/close achievements
- [x] Add friends

**Comment by Moorkopsoesje** [comment]
What exactly do you mean by the dashboard? Since these aren't the watched achievements, do you mean that these are the achievements that you've unlocked? Isn't this easier to show in the list with all achievements, showing the unlocked ones at the top?

**Comment by evankos** [comment]
You can give it a try, the API supports getting all achivements and the unlocked ones now. It will only work for authenticated users and you will only have read access to your achievements so let me know if you receive any unexpected 403s
